 #-------------------------------
 # GitHub Actions
 #
 # Copyleft (c) by ssh500 2023.
 #-------------------------------
 
name: My-GithubActions-Basics
env: 
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"
 
on: 
   push:
     branches:
      - master
       
jobs: 
  my_testing:
    runs-on: ubuntu-latest111
    
    steps:
    - name: Print hello message in Testing.
      run: echo "Hello World from Testing job."
  
    - name: Execurse few commands
      run: |
        echo "Message1"
        echo "Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder.
      run: ls -lah   
        
    - name: Git clone my repo.
      run: git clone https://github.com/ssh500/master.git
      
    - name: List current folder.
      run: ls -lahR 
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env: 
      VAR1 : "This is job level Variable1"
      VAR2 : "This is job level Variable2"
    
    steps:
    - name: Print hello message in Deploy.
      run: echo "Hello World from Deploy job."
      
    - name: Print env vars.
      run: |
        echo "VAR1 = ${{ env.VAR1 }}"
        echo "VAR2 = ${{ env.VAR2 }}"
        echo "VAR3 = $SUPER_LOCAL_VAR"
      env:
        SUPER_LOCAL_VAR: "This is the shuper local var."
 
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
    - name: Let's check some packages if they are here.
      run : aws --version
      
    - name: Let's check git version
      run: |
        git --version 
        curl --version
        zip --version
